dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8
#  - openjdk11
# Backwards compatibility with Java 8
#  - oraclejdk8
services:
  - docker

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
  - name: "AllUnitTests"
    before_install:
      - docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=therapist -e POSTGRES_USER=postgres -e POSTGRES_DB=therapist mdillon/postgis postgis
    script: travis_wait 20 mvn test

install: travis_retry mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
