dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
  - name: "AllUnitTests"
    before_install:
      - docker run -d -p 5433:5432 -e POSTGRES_PASSWORD=therapist -e POSTGRES_USER=postgres -e POSTGRES_DB=therapist --name postgis mdillon/postgis
    script: travis_wait 20 ./mvnw test -Dspring.datasource.url=jdbc:postgresql://localhost:5433/therapist

install: travis_retry ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: script
  script: cp .travis/settings.xml $HOME/.m2/settings.xml && ./mvnw clean install -PreleaseDocker -DskipTests
  on:
    branch: master

before_install:
  # troubleshooting info in case of problems
  - docker version
  - docker info
