version: "2"
services:
  therapist-area:
    image: damadden88/therapist-area
    links:
      - postgis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgis:5432/therapist
    ports:
      - 8082:8082

  postgis:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: therapist
      POSTGRES_DB: therapist
